### ISSUE TITLE
Script terminates unexpectedly 

### ISSUE THREAD

**Issue by mmkk20158** [TheLastGimbus/GooglePhotosTakeoutHelper#16]
here is a snippet of the code just before it errors
```

./Takeout/Google Photos/2018-12-16/Screenshot_20181216-162951_eBay.jpg
./Takeout/Google Photos/2018-12-16/20181216_140153.jpg
./Takeout/Google Photos/2018-12-16/20181216_140030.jpg
./Takeout/Google Photos/2018-12-16/Screenshot_20181216-204929_Amazon Shopping.jpg
./Takeout/Google Photos/2018-12-16/IMG_20181216_082603.jpg
./Takeout/Google Photos/2019-05-02/IMG_20190502_203702.jpg
./Takeout/Google Photos/2014-08-22/20140822_191207.jpg
./Takeout/Google Photos/2014-08-22/20140822_191219.jpg
./Takeout/Google Photos/2014-08-22/20140822_190221.jpg
./Takeout/Google Photos/2014-08-22/20140822_190135.jpg
./Takeout/Google Photos/2018-11-30/IMG_20181130_155507.jpg
./Takeout/Google Photos/2018-11-30/IMG_20181130_134550.jpg
./Takeout/Google Photos/2018-11-30/20181130_125101.jpg
./Takeout/Google Photos/2018-11-30/20181130_125109.jpg
./Takeout/Google Photos/2018-11-30/20181130_125049.jpg
./Takeout/Google Photos/2018-11-30/IMG_20181130_155529.jpg
./Takeout/Google Photos/2018-11-30/20181130_125116.jpg
./Takeout/Google Photos/2018-07-29/20180729_105716.jpg
./Takeout/Google Photos/2020-07-27/20200727_163130.jpg
Couldnt insert exif!
"dump" got wrong type of exif value.
41729 in Exif IFD. Got as <class 'int'>.
./Takeout/Google Photos/2020-07-27/20200727_125202.jpg
./Takeout/Google Photos/2020-07-27/20200727_141726.jpg
Couldnt insert exif!
"dump" got wrong type of exif value.
41729 in Exif IFD. Got as <class 'int'>.
./Takeout/Google Photos/2020-07-27/20200727_163114.jpg
Couldnt insert exif!
"dump" got wrong type of exif value.
41729 in Exif IFD. Got as <class 'int'>.
./Takeout/Google Photos/2020-07-27/20200727_125204.jpg
./Takeout/Google Photos/2020-07-27/20200727_163055.jpg
Couldnt insert exif!
"dump" got wrong type of exif value.
41729 in Exif IFD. Got as <class 'int'>.
./Takeout/Google Photos/2020-07-27/20200727_125418.jpg
Couldnt insert exif!
"dump" got wrong type of exif value.
41729 in Exif IFD. Got as <class 'int'>.
./Takeout/Google Photos/2020-07-27/20200727_125432(0).jpg
Couldnt insert exif!
"dump" got wrong type of exif value.
41729 in Exif IFD. Got as <class 'int'>.
./Takeout/Google Photos/2020-07-27/20200727_163131.jpg
Couldnt insert exif!
"dump" got wrong type of exif value.
41729 in Exif IFD. Got as <class 'int'>.
./Takeout/Google Photos/2020-07-27/20200727_162926.jpg
Couldnt insert exif!
"dump" got wrong type of exif value.
41729 in Exif IFD. Got as <class 'int'>.
./Takeout/Google Photos/2020-07-27/20200727_163230.jpg
Couldnt insert exif!
"dump" got wrong type of exif value.
41729 in Exif IFD. Got as <class 'int'>.
./Takeout/Google Photos/2020-07-27/20200727_115029_03.jpg
./Takeout/Google Photos/2020-07-27/20200727_115029_04.jpg
./Takeout/Google Photos/2020-07-27/20200727_163115.jpg
Couldnt insert exif!
"dump" got wrong type of exif value.
41729 in Exif IFD. Got as <class 'int'>.
./Takeout/Google Photos/2020-07-27/20200727_125432.jpg
Couldnt insert exif!
"dump" got wrong type of exif value.
41729 in Exif IFD. Got as <class 'int'>.
./Takeout/Google Photos/2020-07-27/20200727_115029_07.jpg
./Takeout/Google Photos/2020-07-27/Screenshot_20200726-205805_Facebook.jpg
./Takeout/Google Photos/2020-07-27/20200727_163049.jpg
Couldnt insert exif!
"dump" got wrong type of exif value.
41729 in Exif IFD. Got as <class 'int'>.
./Takeout/Google Photos/2020-07-27/20200727_141732.jpg
Couldnt insert exif!
"dump" got wrong type of exif value.
41729 in Exif IFD. Got as <class 'int'>.
./Takeout/Google Photos/2020-07-27/20200727_162917.jpg
Couldnt insert exif!
"dump" got wrong type of exif value.
41729 in Exif IFD. Got as <class 'int'>.
./Takeout/Google Photos/2020-07-27/20200727_163333.jpg
Couldnt insert exif!
"dump" got wrong type of exif value.
41729 in Exif IFD. Got as <class 'int'>.
./Takeout/Google Photos/2020-07-27/20200727_162859.jpg
Couldnt insert exif!
"dump" got wrong type of exif value.
41729 in Exif IFD. Got as <class 'int'>.
./Takeout/Google Photos/2020-07-27/20200727_163058.jpg
Couldnt insert exif!
"dump" got wrong type of exif value.
41729 in Exif IFD. Got as <class 'int'>.
./Takeout/Google Photos/2020-07-27/20200727_150035.jpg
./Takeout/Google Photos/2020-07-27/20200727_115029_08.jpg
./Takeout/Google Photos/2020-07-27/20200727_185611.jpg
Couldnt insert exif!
"dump" got wrong type of exif value.
41729 in Exif IFD. Got as <class 'int'>.
./Takeout/Google Photos/2020-07-27/20200727_163412.jpg
Couldnt insert exif!
"dump" got wrong type of exif value.
41729 in Exif IFD. Got as <class 'int'>.
./Takeout/Google Photos/2020-07-27/20200727_115029_01.jpg
./Takeout/Google Photos/2020-07-27/20200727_125151.jpg
./Takeout/Google Photos/2020-07-27/20200727_125158.jpg
./Takeout/Google Photos/2020-07-27/20200727_210649.jpg
Couldnt insert exif!
"dump" got wrong type of exif value.
41729 in Exif IFD. Got as <class 'int'>.
./Takeout/Google Photos/2020-07-27/20200727_125421.jpg
Couldnt insert exif!
"dump" got wrong type of exif value.
41729 in Exif IFD. Got as <class 'int'>.
./Takeout/Google Photos/2020-07-27/20200727_163216.jpg
Traceback (most recent call last):
  File "/usr/local/bin/google-photos-takeout-helper", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/google_photos_takeout_helper/__main__.py", line 356, in main
    filter_fun=lambda f: (is_photo(f) or is_video(f))
  File "/usr/local/lib/python3.7/dist-packages/google_photos_takeout_helper/__main__.py", line 99, in for_all_files_recursive
    for_all_files_recursive(file, file_function, folder_function, filter_fun)
  File "/usr/local/lib/python3.7/dist-packages/google_photos_takeout_helper/__main__.py", line 99, in for_all_files_recursive
    for_all_files_recursive(file, file_function, folder_function, filter_fun)
  File "/usr/local/lib/python3.7/dist-packages/google_photos_takeout_helper/__main__.py", line 99, in for_all_files_recursive
    for_all_files_recursive(file, file_function, folder_function, filter_fun)
  File "/usr/local/lib/python3.7/dist-packages/google_photos_takeout_helper/__main__.py", line 102, in for_all_files_recursive
    file_function(dir, file)
  File "/usr/local/lib/python3.7/dist-packages/google_photos_takeout_helper/__main__.py", line 274, in fix_metadata
    set_creation_date_from_exif(file)
  File "/usr/local/lib/python3.7/dist-packages/google_photos_takeout_helper/__main__.py", line 230, in set_creation_date_from_exif
    exif_dict = _piexif.load(file)
  File "/usr/local/lib/python3.7/dist-packages/piexif/_load.py", line 53, in load
    exif_dict["1st"] = exifReader.get_ifd_dict(pointer, "1st")
  File "/usr/local/lib/python3.7/dist-packages/piexif/_load.py", line 109, in get_ifd_dict
    self.tiftag[pointer: pointer+2])[0]
struct.error: unpack requires a buffer of 2 bytes

```

**Comment by TheLastGimbus** [comment]
This looks like something completely broken with exif. Thats is - completely out of my reach and pointless to individually detect (when it happens) and fix

So - I will probably need to add wider `try-catch` - but for now, cut it out individually and move on...

**Comment by mmkk20158** [comment]
Cut out which file?

**Comment by TheLastGimbus** [comment]
The one that caused exception, e.g. last logged e.g. `./Takeout/Google Photos/2020-07-27/20200727_163216.jpg`
