### ISSUE TITLE
PathNotFoundException caused by leading or trailing spaces in file/directory names

### ISSUE THREAD

**Issue by a-chen** [TheLastGimbus/GooglePhotosTakeoutHelper#212]
Hi, ran into an issue caused by a trailing space somehow showing up at the end of one of my directories in the example below. The exception caused the program to exit.
```
PathNotFoundException: Cannot rename file to 'output\2021.06.20 wedding shower \2021-06-20 14_42_48-Zoom Meeting.png', path = 'input\Takeout\Google Photos\2021.06.20 wedding shower \2021-06-20 14_42_48-Zoom Meeting.png' (OS Error: The system cannot find the path specified.
, errno = 3)
#0      _checkForErrorResponse (dart:io/common.dart:42)
#1      _File.rename.<anonymous closure> (dart:io/file_impl.dart:318)
<asynchronous suspension>
#2      moveFiles.moveFile (package:gpth/moving.dart:132)
<asynchronous suspension>
#3      moveFiles (package:gpth/moving.dart:153)
<asynchronous suspension>
#4      main.<anonymous closure> (file:///d:/a/googlephotostakeouthelper/googlephotostakeouthelper/bin/gpth.dart:365)
<asynchronous suspension>
```

### Being lazy, I asked ChatGPT where to make the change in `moving.dart`
"I encountered an error that seems to be caused by a space at the end of the folder name in the below error. I think the solution would be to strip leading and trailing empty characters of file and folder names. Where should this change be made?"

and it recommended the following changes. Looked mostly correct to me, so am reporting this issue. Hope this helps! Greatly appreciate your work

### ChatGPT response
The change should be made where the file and folder paths are being constructed, specifically where the folder's name is defined and where the file is being moved or copied to.

Here is where you can make the changes:

Line 83-90: This is where the folder path is constructed. You can use Dart's trim method to remove leading and trailing white spaces from the file and folder names. Replace the existing lines with the following code:

```dart
final folder = Directory(
  p.join(
    output.path,
    (file.key ?? 'ALL_PHOTOS').trim(), // album or all
    divideToDates
        ? date == null
            ? 'date-unknown'.trim()
            : p.join(
                '${date.year}'.trim(),
                date.month.toString().padLeft(2, '0').trim(),
              )
        : '',
  ),
);
```
Line 107-110: This is where the file is being moved or copied. Again, you should trim the filename here:
```dart
final freeFile = findNotExistingName(
    File(p.join(folder.path, p.basename(file.value.path).trim())));
```
After these changes, your program should work correctly with folder or file names that have leading or trailing spaces.

**Comment by a-chen** [comment]
Seems to be a Windows thing
https://stackoverflow.com/questions/74936903/why-do-some-os-functions-ignore-trailing-spaces-on-windows
