### ISSUE TITLE
The system cannot move the file to a different disk drive

### ISSUE THREAD

**Issue by labba** [TheLastGimbus/GooglePhotosTakeoutHelper#259]
i have the take out on one disk and wanted the output to another disk drive, while trying to execute the gpth-windoza.exe v3.4.3, i gotten the following exception:

```
Finding albums (this may take some time, dont worry :) ...
Moving photos to output folder : ........................................ 0/30033  Unhandled exception:


FileSystemException: Cannot rename file to 'D:\out\ALL_PHOTOS\2017\12\IMG-20171218-WA0009.jpg', path = 'C:\Users\user\Downloads\achi\in\takeout-20231022T182402Z-001\Takeout\Google Photos\Photos from 2017\IMG-20171218-WA0009.jpg' (OS Error: The system cannot move the file to a different disk drive.
, errno = 17)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.rename.<anonymous closure> (dart:io/file_impl.dart:335)
<asynchronous suspension>
#2      moveFiles.moveFile (package:gpth/moving.dart:135)
<asynchronous suspension>
#3      moveFiles (package:gpth/moving.dart:140)
<asynchronous suspension>
#4      main.<anonymous closure> (file:///d:/a/googlephotostakeouthelper/googlephotostakeouthelper/bin/gpth.dart:373)
<asynchronous suspension>

```

i saw this issue and solution reported on stackoverflow.com: https://stackoverflow.com/questions/21116510/python-oserror-winerror-17-the-system-cannot-move-the-file-to-a-different-d

hope this help.

**Comment by TheLastGimbus** [comment]
Duplicate of #251 

See my response there: https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/issues/251#issuecomment-1747006340
