### ISSUE TITLE
Photos taken before 01.01.1970

### ISSUE THREAD

**Issue by Tschi02** [TheLastGimbus/GooglePhotosTakeoutHelper#32]
When there is a negativ time in epoche seconds in the json file, the script ends with an exception. 
All dates before 01.01.1970 00:00:01 have a negative one, tho.

**Comment by TheLastGimbus** [comment]
Can you paste the exception (in a code block) here, please?

**Comment by Tschi02** [comment]
Sure:

`Fixing files metadata and creation dates...
=====================
C:\Users\*****\Desktop\Takeout/Google Fotos/1965-05-01/EPSON003.JPG
No creation date found in exif!
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\google_photos_takeout_helper\__main__.py", line 623, in <module>
    main()
  File "C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\google_photos_takeout_helper\__main__.py", line 562, in main
    for_all_files_recursive(
  File "C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\google_photos_takeout_helper\__main__.py", line 125, in for_all_files_recursive
    for_all_files_recursive(file, file_function, folder_function, filter_fun)
  File "C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\google_photos_takeout_helper\__main__.py", line 125, in for_all_files_recursive
    for_all_files_recursive(file, file_function, folder_function, filter_fun)
  File "C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\google_photos_takeout_helper\__main__.py", line 128, in for_all_files_recursive
    file_function(dir, file)
  File "C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\google_photos_takeout_helper\__main__.py", line 488, in fix_metadata
    date = get_date_str_from_json(google_json)
  File "C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\google_photos_takeout_helper\__main__.py", line 370, in get_date_str_from_json
    return _datetime.fromtimestamp(
OSError: [Errno 22] Invalid argument`

**Comment by TheLastGimbus** [comment]
Really weird, I just tested it (on Ubuntu) with `-12000` in `.json`, and it works perfectly, date was set to `31.12.1969 21:40:00`

This seems to be an issue of Windows/old Windows/old Python, so I'll close this anyway. Try to update stuff etc...

**Comment by Tschi02** [comment]
That's fine with me. Even though I have the latest Windows 2004 and Python 3.9.1 installed.
