### ISSUE TITLE
FileSystemException: Cannot rename file ...... (OS Error: Invalid cross-device link, errno = 18)

### ISSUE THREAD

**Issue by Coll147** [TheLastGimbus/GooglePhotosTakeoutHelper#363]
Hi, I was trying to use the tool, but it shows this error when it tries to copy the images, or something like that I understand. I have tested both on a Windows 11 computer and on Arch Linux. The takeout folder is located on a USB hard drive and the destination folder is located on another drive. Maybe that affects it, that's why I'm giving the information. Well, I hope you can help me, thanks.
```
Finding albums (this may take some time, dont worry :) ...
Moving photos to output folder : ........................................ 0/80339  Unhandled exception:
FileSystemException: Cannot rename file to '/run/media/coll147/SD PODEROSA/ALL_PHOTOS/17d8d47531be3eb4fb19fc73636fbb533addeba5dc8df04f38.jpg', path = '/run/media/coll147/500GB/Takeout/Google Fotos/Photos from 2005/17d8d47531be3eb4fb19fc73636fbb533addeba5dc8df04f38.jpg' (OS Error: Invalid cross-device link, errno = 18)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.rename.<anonymous closure> (dart:io/file_impl.dart:335)
<asynchronous suspension>
#2      moveFiles.moveFile (package:gpth/moving.dart:135)
<asynchronous suspension>
#3      moveFiles (package:gpth/moving.dart:140)
<asynchronous suspension>
#4      main.<anonymous closure> (file:///home/runner/work/GooglePhotosTakeoutHelper/GooglePhotosTakeoutHelper/bin/gpth.dart:373)
<asynchronous suspension>
```

**Comment by TheLastGimbus** [comment]
see #251
