### ISSUE TITLE
Invalid Name

### ISSUE THREAD

**Issue by sugarfunk** [TheLastGimbus/GooglePhotosTakeoutHelper#45]
Hi, 

This my be my error, but I cannot seem to work through this. Below is the error thrown. It isn't singled out to this file. I previously had this error, deleted the file, and reran and had the same error on a different file. 

```python
/volume1/public/takeout/1main/Takeout/Google Photos/kbday/IMG_20190203_163316.jpg
/volume1/public/takeout/1main/Takeout/Google Photos/kbday/IMG_20181230_110012.jpg
/volume1/public/takeout/1main/Takeout/Google Photos/kbday/MVIMG_20190218_162639.jpg
/volume1/public/takeout/1main/Takeout/Google Photos/kbday/IMG_20190214_122032.jpg
/volume1/public/takeout/1main/Takeout/Google Photos/kbday/IMG_20190313_071319.jpg
/volume1/public/takeout/1main/Takeout/Google Photos/kbday/IMG_20190313_202224.jpg
Traceback (most recent call last):
  File "/var/services/homes/admin42/.local/bin/google-photos-takeout-helper", line 8, in <module>
    sys.exit(main())
  File "/var/services/homes/admin42/.local/lib/python3.8/site-packages/google_photos_takeout_helper/__main__.py", line 570, in main
    for_all_files_recursive(
  File "/var/services/homes/admin42/.local/lib/python3.8/site-packages/google_photos_takeout_helper/__main__.py", line 113, in for_all_files_recursive
    if filter_fun(file):
  File "/var/services/homes/admin42/.local/lib/python3.8/site-packages/google_photos_takeout_helper/__main__.py", line 573, in <lambda>
    filter_fun=lambda f: (is_photo(f) or is_video(f))
  File "/var/services/homes/admin42/.local/lib/python3.8/site-packages/google_photos_takeout_helper/__main__.py", line 133, in is_photo
    plain_file = file.with_name(_re.sub(search, '.', str(file)))
  File "/var/packages/py3k/target/usr/local/lib/python3.8/pathlib.py", line 847, in with_name
    raise ValueError("Invalid name %r" % (name))
ValueError: Invalid name '/volume1/public/takeout/1main/Takeout/Google Photos/kbday/MVIMG_20190427_154630.jpg'
```

**Comment by sugarfunk** [comment]
its related to the flag '--skip-extras-harder'. '--skip-extras' eliminates this error

**Comment by TheLastGimbus** [comment]
Then don't use any of those options :+1: problem solved :100:

**Comment by sugarfunk** [comment]
> Then don't use any of those options 👍 problem solved 💯

Yup, thats what I did. just flagging it for troubleshooting.

**Comment by TheLastGimbus** [comment]
> flagging it for troubleshooting

Thx for that, this may help in future
