### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'read_text'

### ISSUE THREAD

**Issue by nilinyi** [TheLastGimbus/GooglePhotosTakeoutHelper#47]
Cannot install the version 2.0.0rc1 due to error `AttributeError: 'PosixPath' object has no attribute 'read_text'`

```
➜  ~ pip install -U google-photos-takeout-helper==2.0.0rc1
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting google-photos-takeout-helper==2.0.0rc1
  Using cached google-photos-takeout-helper-2.0.0rc1.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/w5/y72p307x293dfngw87fm1m9w0000gn/T/pip-install-YHKLMj/google-photos-takeout-helper/setup.py'"'"'; __file__='"'"'/private/var/folders/w5/y72p307x293dfngw87fm1m9w0000gn/T/pip-install-YHKLMj/google-photos-takeout-helper/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/w5/y72p307x293dfngw87fm1m9w0000gn/T/pip-pip-egg-info-0x10iB
         cwd: /private/var/folders/w5/y72p307x293dfngw87fm1m9w0000gn/T/pip-install-YHKLMj/google-photos-takeout-helper/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/w5/y72p307x293dfngw87fm1m9w0000gn/T/pip-install-YHKLMj/google-photos-takeout-helper/setup.py", line 6, in <module>
        README = (HERE/"README.md").read_text()
    AttributeError: 'PosixPath' object has no attribute 'read_text'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
➜  ~ which python  
/Library/Frameworks/Python.framework/Versions/2.7/bin/python
➜  ~ which pip   
/Library/Frameworks/Python.framework/Versions/2.7/bin/pip
```

**Comment by nilinyi** [comment]
Using `pip3` instead actually solves my issue:
` ~ pip3 install -U google-photos-takeout-helper==2.0.0rc1`
