### ISSUE TITLE
Error: "unpack requires a buffer of 2 bytes"

### ISSUE THREAD

**Issue by zkvvoob** [TheLastGimbus/GooglePhotosTakeoutHelper#50]
Hello!

First of all, thank you for working so hard to make this tool work. I've been watching it since the beginning, waiting for your to add GPS and now that it's available in version 2, I've re-downloaded my Google Photos and tried running the Takeout Helper. 

Unfortunately, twice it failed with the following error. I tried adding --user at the end, but the argument was not accepted.

```python
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\google-photos-takeout-helper.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\google_photos_takeout_helper\__main__.py", line 570, in main
    for_all_files_recursive(
  File "c:\programdata\anaconda3\lib\site-packages\google_photos_takeout_helper\__main__.py", line 114, in for_all_files_recursive
    file_function(file)
  File "c:\programdata\anaconda3\lib\site-packages\google_photos_takeout_helper\__main__.py", line 494, in fix_metadata
    set_creation_date_from_exif(file)
  File "c:\programdata\anaconda3\lib\site-packages\google_photos_takeout_helper\__main__.py", line 343, in set_creation_date_from_exif
    exif_dict = _piexif.load(str(file))
  File "c:\programdata\anaconda3\lib\site-packages\piexif\_load.py", line 53, in load
    exif_dict["1st"] = exifReader.get_ifd_dict(pointer, "1st")
  File "c:\programdata\anaconda3\lib\site-packages\piexif\_load.py", line 108, in get_ifd_dict
    tag_count = struct.unpack(self.endian_mark + "H",
struct.error: unpack requires a buffer of 2 bytes
```

Running on WIndows 10 x64, Python 3.8.5

**Comment by TheLastGimbus** [comment]
You seem to be running anaconda. I didn't really had much experience with it, and don't know how much it can break, but it probably can...

Can you make a new python venv, pip install in it, and then see if it works/new errors?

```cmd
cd C:\Folder\Wherever\You\Want

python -m venv myenv
myenv\Scripts\activate.bat
pip install -U google-photos-takeout-helper
<the_rest_of_instructions>
```
And hope that anaconda doesn't interrupt with that...

**Comment by TheLastGimbus** [comment]
And here we go again - standard procedure - can you provide me a sample of file that caused this? Maybe try to find couple of such files, by cutting them out and running again...

**Comment by zkvvoob** [comment]
I removed the last 3 photos before the error message and the script finished successfully. Thank you very much for your help!

**Comment by TheLastGimbus** [comment]
No need to cut out last three - only last one that was printed

Happy that it worked!
