### ISSUE TITLE
UnicodeEncodeError after all files are processed

### ISSUE THREAD

**Issue by weak-head** [TheLastGimbus/GooglePhotosTakeoutHelper#78]
The script crashes with `UnicodeEncodeError` after all files are processed.

Here is the log file:
```
2021-03-09 19:48:06.723 | INFO     | __main__:main:697 - DONE! FREEEEEDOOOOM!!!
2021-03-09 19:48:06.723 | INFO     | __main__:main:698 - 
2021-03-09 19:48:06.724 | INFO     | __main__:main:699 - Final statistics:
2021-03-09 19:48:06.724 | INFO     | __main__:main:700 - Files copied to target folder: 37766
2021-03-09 19:48:06.724 | INFO     | __main__:main:701 - Removed duplicates: 8196
2021-03-09 19:48:06.724 | INFO     | __main__:main:702 - Files for which we couldn't find json: 969
2021-03-09 19:48:06.726 | INFO     | __main__:main:708 -  - you have full list in alex\no_json_found.txt
2021-03-09 19:48:06.736 | INFO     | __main__:main:709 - Files where inserting new exif failed: 2390
2021-03-09 19:48:06.737 | INFO     | __main__:main:711 - (This is not necessary bad thing - pretty much all videos fail, and your photos probably have their original exif already
2021-03-09 19:48:06.739 | INFO     | __main__:main:717 -  - you have full list in alex\failed_inserting_exif.txt
2021-03-09 19:48:06.752 | INFO     | __main__:main:718 - Files where date was set from name of the folder: 91
2021-03-09 19:48:06.758 | ERROR    | __main__:<module>:754 - WHHoopssiee! Looks like script crashed! This shouldn't happen, although it often does haha :P
Most of the times, you should cut out the last printed file (it should be down there somehwere) to some other folder, and continue

If this doesn't help, and it keeps doing this after many cut-outs, you can check out issues tab:
https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/issues 
to see if anyone has similar issue, or contact me other way:
https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/blob/master/README.md#contacterrors 

Traceback (most recent call last):

> File "google_photos_takeout_helper\__main__.py", line 754, in <module>

  File "google_photos_takeout_helper\__main__.py", line 723, in main

  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\encodings\cp1252.py", line 19, in encode

UnicodeEncodeError: 'charmap' codec can't encode characters in position 49-60: character maps to <undefined>
```

**Comment by TheLastGimbus** [comment]
Oh, this was fixed in #75, but I didn't release it yet :sweat_smile:
