### ISSUE TITLE
Permission denied (Errno 13)

### ISSUE THREAD

**Issue by studied-sermon-gender** [TheLastGimbus/GooglePhotosTakeoutHelper#89]
Hey there

I am trying to get the Takeout Helper to work, but ran into some issue. Here's the log:

```
2021-05-12 19:32:04.785 | INFO     | __main__:main:99 - Heeeere we go!
2021-05-12 19:32:04.800 | INFO     | __main__:main:655 - Counting how many input files we have ahead...
2021-05-12 19:32:08.516 | INFO     | __main__:main:659 - Input files: 3195
2021-05-12 19:32:08.516 | INFO     | __main__:main:661 - =====================
2021-05-12 19:32:08.517 | INFO     | __main__:main:662 - Fixing files metadata and creation dates...
2021-05-12 19:32:09.261 | DEBUG    | __main__:set_creation_date_from_exif:436 - Wrong date format in exif!
2021-05-12 19:32:09.262 | DEBUG    | __main__:set_creation_date_from_exif:437 - 2018:07:31 13:05:32
2021-05-12 19:32:09.262 | DEBUG    | __main__:set_creation_date_from_exif:438 - does not match '%Y:%m:%d %H:%M:%S'
2021-05-12 19:32:09.262 | DEBUG    | __main__:set_creation_date_from_exif:436 - Wrong date format in exif!
2021-05-12 19:32:09.263 | DEBUG    | __main__:set_creation_date_from_exif:437 - 2018:07:31 13:05:32
2021-05-12 19:32:09.263 | DEBUG    | __main__:set_creation_date_from_exif:438 - does not match '%Y:%m:%d %H:%M:%S'
2021-05-12 19:32:09.264 | DEBUG    | __main__:set_creation_date_from_exif:436 - Wrong date format in exif!
2021-05-12 19:32:09.264 | DEBUG    | __main__:set_creation_date_from_exif:437 - 2018:07:31 13:05:32
2021-05-12 19:32:09.264 | DEBUG    | __main__:set_creation_date_from_exif:438 - does not match '%Y:%m:%d %H:%M:%S'
2021-05-12 19:32:09.264 | DEBUG    | __main__:fix_metadata:580 - No correct DateTime in given exif
2021-05-12 19:32:09.265 | DEBUG    | __main__:fix_metadata:581 - No exif for C:\Users\fg\Desktop\takeout\Archiv\00005IMG_00005_BURST20180731130532.jpg
2021-05-12 19:32:09.287 | DEBUG    | __main__:set_file_geo_data:565 - Couldn't insert geo exif!
2021-05-12 19:32:09.288 | DEBUG    | __main__:set_file_geo_data:567 - [Errno 13] Permission denied: 'C:\\Users\\fg\\Desktop\\takeout\\Archiv\\00005IMG_00005_BURST20180731130532.jpg'
2021-05-12 19:32:09.313 | DEBUG    | __main__:set_file_exif_date:456 - Couldn't insert exif!
2021-05-12 19:32:09.314 | DEBUG    | __main__:set_file_exif_date:457 - [Errno 13] Permission denied: 'C:\\Users\\fg\\Desktop\\takeout\\Archiv\\00005IMG_00005_BURST20180731130532.jpg'
2021-05-12 19:32:09.317 | ERROR    | __main__:<module>:773 - WHHoopssiee! Looks like script crashed! This shouldn't happen, although it often does haha :P
Most of the times, you should cut out the last printed file (it should be down there somehwere) to some other folder, and continue

If this doesn't help, and it keeps doing this after many cut-outs, you can check out issues tab:
https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/issues 
to see if anyone has similar issue, or contact me other way:
https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/blob/master/README.md#contacterrors 

Traceback (most recent call last):

  File "google_photos_takeout_helper\__main__.py", line 412, in set_creation_date_from_str

PermissionError: [WinError 5] Zugriff verweigert: 'C:\\Users\\fg\\Desktop\\takeout\\Archiv\\00005IMG_00005_BURST20180731130532.jpg'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

> File "google_photos_takeout_helper\__main__.py", line 773, in <module>

  File "google_photos_takeout_helper\__main__.py", line 670, in main

  File "google_photos_takeout_helper\__main__.py", line 152, in for_all_files_recursive

  File "google_photos_takeout_helper\__main__.py", line 668, in <lambda>

  File "google_photos_takeout_helper\__main__.py", line 590, in fix_metadata

  File "google_photos_takeout_helper\__main__.py", line 416, in set_creation_date_from_str

ValueError: Error setting creation date from string: 2018:07:31 11:05:32

```

I don't have any experience with programming, so please forgive me if I'm making an obvious error. But looking at the log, I think it has something to do with the permissions, so I also tried running it in admin mode. That didn't work, either. 

Thanks in advance for any help you can give.

**Comment by TheLastGimbus** [comment]
Hi!
1. Did you install from pip or .exe?
  1.2 If form pip, people on internet suggest to do `pip install <package> --user`
  1.3 If that won't work, maybe try .exe? Or if you use .exe try pip

**Comment by studied-sermon-gender** [comment]
Hey, thanks for the reply!

I was using the .exe so I tried the pip, which then worked. Thanks!
