### ISSUE TITLE
Does it run in macOS?

### ISSUE THREAD

**Issue by wyfang** [TheLastGimbus/GooglePhotosTakeoutHelper#95]
I'm not a developer and I only have macOS, does it work? I tried to run it in terminal, but it says this：

`WANGYIFANGCOM-iMac:~ wifi$ pip install -U google-photos-takeout-helper
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    load_entry_point('pip==21.1.3', 'console_scripts', 'pip')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/pip-21.1.3-py2.7.egg/pip/__init__.py", line 1, in <module>
    from typing import List, Optional
ImportError: No module named typing`

**Comment by ShayanYaseen** [comment]
Could you try using the command
`pip3 install -U google-photos-takeout-helper `


Typing pip3 tells your mac to use python3 (Which is what this tool is written in) to install the tool instead of python2.

**Comment by TheLastGimbus** [comment]
Oh @ShayanYaseen thanks for help! Yes, you see @wyfang, it's kinda a mess with `python` and `python3` and `python2` :sweat_smile: Some systems/installations interpet `python` as 2 (Ubuntu), and some as (Windoza)

Mac may be the same case :+1:

**Comment by wyfang** [comment]
> Could you try using the command
> `pip3 install -U google-photos-takeout-helper `
> 
> Typing pip3 tells your mac to use python3 (Which is what this tool is written in) to install the tool instead of python2.

Thx! It's work. 😄

**Comment by wyfang** [comment]
But after I exported 120,000 photos, there were more than 10,000 duplicate photos they had a (1) duplicate with something like "MG0019(1).jpg". But I used other software (Gemini 2) to automatically identify and delete them.

**Comment by TheLastGimbus** [comment]
> 120,000

# :flushed: 

Damn I **did not** suspect this script won't crap itself with that amount :sweat_smile: - did you maybe see any RAM issues while running? Some people had...
